install.packages('plyr', version="1.8.4", repos='http://cran.us.r-project.org')
install.packages('dplyr', version="0.8.3", repos='http://cran.us.r-project.org')
install.packages('scales', version="1.0.0", repos='http://cran.us.r-project.org')
install.packages('lubridate', version="1.7.4", repos='http://cran.us.r-project.org')
install.packages('magrittr', version="1.5", repos='http://cran.us.r-project.org')
install.packages('data.table', version="1.11.8", repos='http://cran.us.r-project.org')
install.packages('httr', version="1.3.1", repos='http://cran.us.r-project.org')
install.packages('reshape2', version="1.4.3", repos='http://cran.us.r-project.org')
