# Use an official Python runtime as a parent image
FROM debian:jessie-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD generate_sources.sh /app

# Install any needed packages
RUN mkdir /usr/share/man/man1/
RUN touch /usr/share/man/man1/java.1.gz.dpkg-tmp
RUN bash /app/generate_sources.sh

RUN apt-get update
RUN apt-get --yes --allow-unauthenticated install sudo
RUN apt-get install --yes --allow-unauthenticated oracle-j2sdk1.8
RUN apt-get install --yes --allow-unauthenticated apt-utils
RUN apt-get install --yes --allow-unauthenticated pkg-config

RUN apt-get install --yes --allow-unauthenticated python-pip
RUN apt-get install --yes --allow-unauthenticated python-thrift-binding
RUN apt-get install --yes --allow-unauthenticated python-jsonpickle
RUN apt-get install --yes --allow-unauthenticated python-pandas
RUN apt-get install --yes --allow-unauthenticated python-gurobi

RUN sudo apt-get remove python-numpy
RUN sudo pip install numpy==1.14.0
RUN pip install pyaml
RUN python -m pip install --upgrade pip
RUN sudo apt-get remove python-pip
RUN pip install tqdm==4.19.5
RUN pip install scikit-learn==0.19.1
RUN pip install torch==0.3.1
RUN pip install --upgrade pandas==0.23.4
RUN pip install scipy
